### ISSUE TITLE
Precommit hook results in error

### ISSUE THREAD

**Issue by biprateep** [lincc-frameworks/python-project-template#191]
Hi
I see this error for the recommit hook which checks the template version. This results in a failed commit.  I am pasting the error below. For now, I have commented out the specific section from the `.pre-commit-config.yaml` file to make the commits 

> work.Check template version...................................................Failed
- hook id: check-lincc-frameworks-template-version
- duration: 0.1s
- exit code: 1

Traceback (most recent call last):
  File "/home/biprateep/.cache/pre-commit/reponuhoh0k3/py_env-python3.9/bin/check-lincc-frameworks-template-version", line 5, in <module>
    from pre_commit_hooks.check_template_version import main
  File "/home/biprateep/.cache/pre-commit/reponuhoh0k3/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/__init__.py", line 1, in <module>
    from .check_template_version import *
  File "/home/biprateep/.cache/pre-commit/reponuhoh0k3/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_template_version.py", line 60, in <module>
    def main(argv: Sequence[str] | None = None) -> int:
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

**Comment by drewoldag** [comment]
@biprateep thanks for reporting this error, could you tell me which version of Python you're using when you see the error?

**Comment by drewoldag** [comment]
This seems to actually be a problem with the pre-commit hook itself. I took a swing at fixing it with this PR https://github.com/lincc-frameworks/pre-commit-hooks/pull/5 

@biprateep if you have a moment, try uncommenting the lines in pre-commit.yaml to see if the new version fixes the problem that you were encountering.

**Comment by biprateep** [comment]
@drewoldag Simply uncommenting the lines did not fix the issue. Though when I manually updated the rev attribute for the pre-commit hook repo to 0.1.1, it fixed the issue. Thanks for solving this.
