### ISSUE TITLE
Git init option only works with git >= 2.28

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#193]
The cmu math servers are running git version 2.25.1, which doesn't understand the `--initial-branch` option.

```
 > Running task 1 of 1: git init --initial-branch=main
error: unknown option `initial-branch=main'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree

Traceback (most recent call last):
  File "/export/home/phys/delucchi/anaconda3/envs/tables_io/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
             ^^^^^^^^^^^^^^^^
  File "/export/home/phys/delucchi/anaconda3/envs/tables_io/lib/python3.11/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/home/phys/delucchi/anaconda3/envs/tables_io/lib/python3.11/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/export/home/phys/delucchi/anaconda3/envs/tables_io/lib/python3.11/site-packages/copier/cli.py", line 68, in _wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/home/phys/delucchi/anaconda3/envs/tables_io/lib/python3.11/site-packages/copier/cli.py", line 295, in main
    ).run_copy()
      ^^^^^^^^^^
  File "/export/home/phys/delucchi/anaconda3/envs/tables_io/lib/python3.11/site-packages/copier/main.py", line 719, in run_copy
    self._execute_tasks(self.template.tasks)
  File "/export/home/phys/delucchi/anaconda3/envs/tables_io/lib/python3.11/site-packages/copier/main.py", line 250, in _execute_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "/export/home/phys/delucchi/anaconda3/envs/tables_io/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git init --initial-branch=main' returned non-zero exit status 129.
```

```
(tables_io) delucchi@fp81:~/git/rail_hub$ git --version
git version 2.25.1
```

See also Issue #140.

**Comment by drewoldag** [comment]
Related to #140

**Comment by cchris28** [comment]
Possibly we could use: "git init && git branch -m master main 2>/dev/null"

If the current branch is already main (this could be set with .gitconfig) then the 2nd command fails. Hence the redirect

**Comment by drewoldag** [comment]
Given that the work in PR #214 is merged in, then the location to make these changes moves from `copier.yml` to `./python-project-template/tmp/_prepare_project.sh`.
