### ISSUE TITLE
copier 8.0 breaks CI

### ISSUE THREAD

**Issue by cchris28** [lincc-frameworks/python-project-template#212]
Lots of cli changes some of which break our CI

https://github.com/copier-org/copier/releases/tag/v8.0.0

See, for example
https://github.com/lincc-frameworks/python-project-template/actions/runs/5171494987/jobs/9315697407?pr=210

**Comment by cchris28** [comment]
wrote an interim patch to avoid problem.
This resolves the issue for now but we need a more extensive fix. I tried Drew's suggestion of putting he options after the command but that did not work (other issues it seems)

**Comment by drewoldag** [comment]
There are lots of breaking changes associated with the Copier 8.0.0 release. And not all of them are documented, nor has the documentation been updated to reflect all the changes. 

1. All CLI copier commands must now be `copier [copy|update|recopy] <any flags like --vsc-ref=HEAD, --force, ...> 
2. It looks like we can't use tasks to do `git init; --initial-branch=main` anymore because tasks are "unsafe features"

More to be discovered...

**Comment by drewoldag** [comment]
Attempting to run `pip install -e .` without first manually running `git init` will produce the following error: 

```
error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Traceback (most recent call last):
        File "/home/drew/miniconda3/envs/scratch/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/drew/miniconda3/envs/scratch/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/drew/miniconda3/envs/scratch/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 496, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 935, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 127, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 63, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-1srj29to/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 108, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /home/drew/code/science.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Note the line: "Make sure you're either building from a fully intact git repository".

**Comment by drewoldag** [comment]
To use tasks, we have to explicitly pass `--UNSAFE` flag. This could be really difficult to sell to new users going forward.

**Comment by drewoldag** [comment]
Seems like the general consensus is to roll forward with Copier 8.0. I believe that the list of required changes are:

- Require a minimum version of copier for creating a new project or updating a template
- Updating the documentation in many places
- Request that the user pass a `--UNSAFE` flag when they copy or update a project

Judging by the comments in the discussion for Copier, we are not the only users affected by this, and so far, the response to the `--UNSAFE`` flag has not been positive. So perhaps a new version of copier will be released shortly that addresses this.
